allowBuilds:
  better-sqlite3: set this to true or false
  electron: true
  electron-winstaller: true
  esbuild: true
  msw: set this to true or false
  sharp: true
  unrs-resolver: set this to true or false
