/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as _appRouteImport } from './routes/__app'
import { Route as _appIndexRouteImport } from './routes/__app/index'
import { Route as _appWriteRouteImport } from './routes/__app/write'
import { Route as _appPromptsRouteImport } from './routes/__app/prompts'
import { Route as _appHabitsRouteImport } from './routes/__app/habits'

const _appRoute = _appRouteImport.update({
  id: '/__app',
  getParentRoute: () => rootRouteImport,
} as any)
const _appIndexRoute = _appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => _appRoute,
} as any)
const _appWriteRoute = _appWriteRouteImport.update({
  id: '/write',
  path: '/write',
  getParentRoute: () => _appRoute,
} as any)
const _appPromptsRoute = _appPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => _appRoute,
} as any)
const _appHabitsRoute = _appHabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => _appRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof _appIndexRoute
  '/habits': typeof _appHabitsRoute
  '/prompts': typeof _appPromptsRoute
  '/write': typeof _appWriteRoute
}
export interface FileRoutesByTo {
  '/habits': typeof _appHabitsRoute
  '/prompts': typeof _appPromptsRoute
  '/write': typeof _appWriteRoute
  '/': typeof _appIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/__app': typeof _appRouteWithChildren
  '/__app/habits': typeof _appHabitsRoute
  '/__app/prompts': typeof _appPromptsRoute
  '/__app/write': typeof _appWriteRoute
  '/__app/': typeof _appIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/habits' | '/prompts' | '/write'
  fileRoutesByTo: FileRoutesByTo
  to: '/habits' | '/prompts' | '/write' | '/'
  id:
    | '__root__'
    | '/__app'
    | '/__app/habits'
    | '/__app/prompts'
    | '/__app/write'
    | '/__app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  _appRoute: typeof _appRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__app': {
      id: '/__app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof _appRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__app/': {
      id: '/__app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof _appIndexRouteImport
      parentRoute: typeof _appRoute
    }
    '/__app/write': {
      id: '/__app/write'
      path: '/write'
      fullPath: '/write'
      preLoaderRoute: typeof _appWriteRouteImport
      parentRoute: typeof _appRoute
    }
    '/__app/prompts': {
      id: '/__app/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof _appPromptsRouteImport
      parentRoute: typeof _appRoute
    }
    '/__app/habits': {
      id: '/__app/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof _appHabitsRouteImport
      parentRoute: typeof _appRoute
    }
  }
}

interface _appRouteChildren {
  _appHabitsRoute: typeof _appHabitsRoute
  _appPromptsRoute: typeof _appPromptsRoute
  _appWriteRoute: typeof _appWriteRoute
  _appIndexRoute: typeof _appIndexRoute
}

const _appRouteChildren: _appRouteChildren = {
  _appHabitsRoute: _appHabitsRoute,
  _appPromptsRoute: _appPromptsRoute,
  _appWriteRoute: _appWriteRoute,
  _appIndexRoute: _appIndexRoute,
}

const _appRouteWithChildren = _appRoute._addFileChildren(_appRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  _appRoute: _appRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.ts'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
